export const TODO_CREATE = 'TODO_CREATE';
export const TODO_CREATE_SUCCEEDED = 'TODO_CREATE_SUCCEEDDED';
export const TODO_UPDATE = 'TODO_UPDATE';
export const TODO_UPDATE_SUCCEEDED = 'TODO_UPDATE_SUCCEEDDED';
export const TODO_DELETE = 'TODO_DELETE';
export const TODO_DELETE_SUCCEEDED = 'TODO_DELETE_SUCCEEDDED';
